name: PR Preview Comment

on:
  workflow_run:
    workflows: ["Build and Deploy Documentation"]
    types:
      - completed

permissions:
  pull-requests: write
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    
    steps:
    - name: Comment on PR
      uses: actions/github-script@v7
      with:
        script: |
          // Get PR number from the workflow run
          const pullRequests = context.payload.workflow_run.pull_requests;
          if (!pullRequests || pullRequests.length === 0) {
            console.log('No pull requests found for this workflow run');
            return;
          }
          
          const prNumber = pullRequests[0].number;
          const runId = context.payload.workflow_run.id;
          const repoOwner = context.repo.owner;
          const repoName = context.repo.repo;
          
          const comment = `## 📚 Documentation Preview
          
          ✅ **Build Status**: Success
          🔗 **Artifacts**: [Download documentation preview](https://github.com/${repoOwner}/${repoName}/actions/runs/${runId})
          
          ### 📋 Build Summary
          - **Multi-language build**: Completed
          - **Chinese docs**: Generated
          - **English docs**: Generated
          - **Build artifacts**: Available for 7 days
          
          ### 🚀 Next Steps
          After merging this PR, the documentation will be automatically deployed to:
          - **Chinese**: https://${repoOwner}.github.io/${repoName}/
          - **English**: https://${repoOwner}.github.io/${repoName}/en/
          
          ---
          *This comment was automatically generated by GitHub Actions*`;
          
          await github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
